require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SolvingStepsController do

  # This should return the minimal set of attributes required to create a valid
  # SolvingStep. As you add validations to SolvingStep, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "service_event_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SolvingStepsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all solving_steps as @solving_steps" do
      solving_step = SolvingStep.create! valid_attributes
      get :index, {}, valid_session
      assigns(:solving_steps).should eq([solving_step])
    end
  end

  describe "GET show" do
    it "assigns the requested solving_step as @solving_step" do
      solving_step = SolvingStep.create! valid_attributes
      get :show, {:id => solving_step.to_param}, valid_session
      assigns(:solving_step).should eq(solving_step)
    end
  end

  describe "GET new" do
    it "assigns a new solving_step as @solving_step" do
      get :new, {}, valid_session
      assigns(:solving_step).should be_a_new(SolvingStep)
    end
  end

  describe "GET edit" do
    it "assigns the requested solving_step as @solving_step" do
      solving_step = SolvingStep.create! valid_attributes
      get :edit, {:id => solving_step.to_param}, valid_session
      assigns(:solving_step).should eq(solving_step)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SolvingStep" do
        expect {
          post :create, {:solving_step => valid_attributes}, valid_session
        }.to change(SolvingStep, :count).by(1)
      end

      it "assigns a newly created solving_step as @solving_step" do
        post :create, {:solving_step => valid_attributes}, valid_session
        assigns(:solving_step).should be_a(SolvingStep)
        assigns(:solving_step).should be_persisted
      end

      it "redirects to the created solving_step" do
        post :create, {:solving_step => valid_attributes}, valid_session
        response.should redirect_to(SolvingStep.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved solving_step as @solving_step" do
        # Trigger the behavior that occurs when invalid params are submitted
        SolvingStep.any_instance.stub(:save).and_return(false)
        post :create, {:solving_step => { "service_event_id" => "invalid value" }}, valid_session
        assigns(:solving_step).should be_a_new(SolvingStep)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SolvingStep.any_instance.stub(:save).and_return(false)
        post :create, {:solving_step => { "service_event_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested solving_step" do
        solving_step = SolvingStep.create! valid_attributes
        # Assuming there are no other solving_steps in the database, this
        # specifies that the SolvingStep created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SolvingStep.any_instance.should_receive(:update_attributes).with({ "service_event_id" => "1" })
        put :update, {:id => solving_step.to_param, :solving_step => { "service_event_id" => "1" }}, valid_session
      end

      it "assigns the requested solving_step as @solving_step" do
        solving_step = SolvingStep.create! valid_attributes
        put :update, {:id => solving_step.to_param, :solving_step => valid_attributes}, valid_session
        assigns(:solving_step).should eq(solving_step)
      end

      it "redirects to the solving_step" do
        solving_step = SolvingStep.create! valid_attributes
        put :update, {:id => solving_step.to_param, :solving_step => valid_attributes}, valid_session
        response.should redirect_to(solving_step)
      end
    end

    describe "with invalid params" do
      it "assigns the solving_step as @solving_step" do
        solving_step = SolvingStep.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SolvingStep.any_instance.stub(:save).and_return(false)
        put :update, {:id => solving_step.to_param, :solving_step => { "service_event_id" => "invalid value" }}, valid_session
        assigns(:solving_step).should eq(solving_step)
      end

      it "re-renders the 'edit' template" do
        solving_step = SolvingStep.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SolvingStep.any_instance.stub(:save).and_return(false)
        put :update, {:id => solving_step.to_param, :solving_step => { "service_event_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested solving_step" do
      solving_step = SolvingStep.create! valid_attributes
      expect {
        delete :destroy, {:id => solving_step.to_param}, valid_session
      }.to change(SolvingStep, :count).by(-1)
    end

    it "redirects to the solving_steps list" do
      solving_step = SolvingStep.create! valid_attributes
      delete :destroy, {:id => solving_step.to_param}, valid_session
      response.should redirect_to(solving_steps_url)
    end
  end

end
